# Generated by Django 5.2.5 on 2025-09-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0004_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
